name: mpy-cross

on:
  push

jobs:
  build-vs:
    strategy:
      fail-fast: false
    env:
      CI_BUILD_CONFIGURATION: "Release"
    runs-on: windows-2022
    steps:
    - uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17, 18)'
    - uses: actions/checkout@v4
    - name: Build mpy-cross.exe
      run: msbuild mpy-cross\mpy-cross.vcxproj -maxcpucount -property:Configuration=Release -property:Platform=x64
    - uses: actions/upload-artifact@v4
      with: 
        path: mpy-cross/build/mpy-cross.exe
    - uses: actions/upload-artifact@v4
      with: 
        name: x64
        path: mpy-cross/build/Releasex64/mpy-cross.exe
